Document: notificador
Title: Debian notificador Manual
Author: <insert document author here>
Abstract: This manual describes what notificador is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/notificador/notificador.sgml.gz

Format: postscript
Files: /usr/share/doc/notificador/notificador.ps.gz

Format: text
Files: /usr/share/doc/notificador/notificador.text.gz

Format: HTML
Index: /usr/share/doc/notificador/html/index.html
Files: /usr/share/doc/notificador/html/*.html

  
