
install:
	mkdir -p $(DESTDIR)/usr/{share/notificador,bin}
	install -C notificador.py $(DESTDIR)/usr/bin/notificador
	install -C alerta $(DESTDIR)/usr/share/notificador/
	install -C utils $(DESTDIR)/usr/share/notificador/
	install -C xmlNotificador $(DESTDIR)/usr/share/notificador
